spring:
  application:
    name: adminWeb
  profiles:
    # 多环境配置
    active: dev
  servlet:
    # 文件上传参数
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: oracle.jdbc.OracleDriver
    druid:
      validation-query-timeout: 2000
      initial-size: 1000
      max-active: 50000
      min-idle: 500
      # 配置获取连接等待超时的时间
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  transaction:
    # 事务处理，失败回滚
    rollback-on-commit-failure: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  resources:
    #配置静态资源目录，会覆盖spring boot默认的静态目录
    static-locations: classpath:/resources/, classpath:/static/
    #启用内容版本策略
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  messages:
    basename: i18n/messages
    encoding: UTF-8

# mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.lz.adminweb.domain
  global-config:
    #是否开启logo
    banner: false
    db-config:
      #主键类型
      id-type: id_worker
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


