server:
  #端口
  port: 9097

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://192.9.102.129:3367/womens_day?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&allowMultiQueries=true
    username: womens
    password: fMEQR68Rdh
  redis:
    # 连接超时时间（毫秒）
    timeout: 2000
    ##redis 单机环境配置
    host: 192.9.102.59
    port: 30010
    password: 3HTzgboy5A2rLio2
    database: 0
    ssl: false
    #redis 集群环境配置
    #    cluster:
    #      nodes: 192.9.102.77:7001,192.9.102.77:7002,192.9.102.77:7003,192.9.102.77:8001,192.9.102.77:8002,192.9.102.77:8003
    #    password: Hsd^73jjs
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 获取连接时的最大等待毫秒数(如果设置为阻塞时BlockWhenExhausted),如果超时就抛异常, 小于零:阻塞不确定的时间,  默认-1
        max-wait: 2000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1
      lettuce:
        pool:
          max-active: 8 #连接池最大连接数（使用负值表示没有限制）
          max-idle: 8   #连接池中的最大空闲连接
          min-idle: 0    # 连接池中的最小空闲连接
          max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
knife4j:
  enable: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

eureka:
  client:
    #打开eureka
    enabled: false

file:
  ## 服务器地址
  windowUrl: D:/files/
  linuxUrl: /usr/local/tomcat/womensadminapi/files/
  image:
    host: https://emergency.szhome.com:32106/

#session过期时间
session:
  #毫秒
  expiration: 15552000000
